# NumPy

In [1]:
import numpy as np

In [57]:
np.random.seed(7)
cities = np.array(["Kathmandu", "Pokhara", "Biratnagar", "Lalitpur", "Birgunj"])
days = np.array([f"D{i:02d}" for i in range(1, 15)])

temps = np.random.randint(14, 36, size=(5, 14)).astype(float)     # °C, 5 cities × 14 days
humidity = np.random.randint(40, 95, size=(5, 14)).astype(float)  # %

temps[2, 5] = np.nan     # sensor outage
temps[4, 11] = np.nan

### B1 — Array anatomy and reshaping (3 pts)
Print temps.shape, .ndim, .dtype, .size. Then build np.arange(70), reshape it to the same shape as temps two ways — with explicit dimensions and with -1 — show the two results are identical, and flatten it. In a comment, explain what -1 asked NumPy to work out, and why reshaping does not copy the data.

In [5]:
print(temps.shape)
print(temps.ndim)
print(temps.dtype)
print(temps.size)

(5, 14)
2
float64
70


In [23]:
arr = np.arange(70)

# Method 1: Explicit dimensions
print("Method 1: Explicit dimensions \n")
reshaped1 = arr.reshape(5,14)
print(reshaped1)

# Method 2: with -1
print("\n Method 2: with -1 \n")
reshaped2 = arr.reshape(5, -1)
print(reshaped2)

print("\nSame: ", np.array_equal(reshaped1, reshaped2))

# flatten
print("\nBefore flatten: ")
print(reshaped1.shape)
print(reshaped2.shape)

print("\nAfter flatten: ")
flattened = reshaped2.flatten()
print("\nFlatten array: ", flattened)
print(flattened.shape)


# -1 tells the numpy to automatically calculate the dimension. Since there are 70 elements and the first value is 
# given as 5 then the numpy calculates the second dimensions as 70 / 5 = 14.

# Reshape doesnot copy the data because it creates a new view with different shape as specified.

Method 1: Explicit dimensions 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63 64 65 66 67 68 69]]

 Method 2: with -1 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63 64 65 66 67 68 69]]

Same:  True

Before flatten: 
(5, 14)
(5, 14)

After flatten: 

Flatten array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
(70,)


### B2 — Indexing and slicing (4 pts)
Using indexing and slicing only, print: (a) Pokhara's day-3 temperature; (b) every city's reading on the last
day; (c) Biratnagar's full fortnight; (d) the block of the first three cities across days 4–8; (e) every other day for
Lalitpur; (f) Kathmandu's fortnight reversed. Print the shape alongside each result.

In [42]:
result = temps[1,2]
print("B2a - Pokhara's day-3 temperature: ", result)
print("B2a - shape: ", result.shape)

result = temps[:, -1]
print("B2b - every city's reading on the last day: ", result)
print("B2b - shape: ", result.shape)

result = temps[2, :]
print("B2c - Biratnagar's full fortnight: ", result)
print("B2c - shape: ", result.shape)

result = temps[0:3, 3:8]
print("B2d - The block of the first three cities across days 4-8: ", result)
print("B2d - shape: ", result.shape)

result = temps[3, 0:14:2]
print("B2e - Every other day for Lalitpur: ", result)
print("B2e - shape: ", result.shape)

result = temps[0, ::-1]
print("B2f - Kathmandu's fortnight reversed: ", result)
print("B2f - shape: ", result.shape)


B2a - Pokhara's day-3 temperature:  14.0
B2a - shape:  ()
B2b - every city's reading on the last day:  [30. 28. 21. 18. 30.]
B2b - shape:  (5,)
B2c - Biratnagar's full fortnight:  [20. 18. 28. 23. 17. nan 22. 33. 30. 15. 14. 30. 26. 21.]
B2c - shape:  (14,)
B2d - The block of the first three cities across days 4-8:  [[33. 21. 28. 22. 28.]
 [25. 20. 33. 26. 19.]
 [23. 17. nan 22. 33.]]
B2d - shape:  (3, 5)
B2e - Every other day for Lalitpur:  [24. 17. 21. 35. 17. 17. 33.]
B2e - shape:  (7,)
B2f - Kathmandu's fortnight reversed:  [30. 18. 20. 21. 22. 24. 28. 22. 28. 21. 33. 17. 18. 29.]
B2f - shape:  (14,)


### B3 — Boolean masks (3 pts)
(a) Build the mask `temps > 30` and print how many readings exceed 30 per city — one number per city, no loop. (b) Print the actual day labels on which Kathmandu exceeded 30, by using the mask to index `days`. (c) In a comment, explain in one sentence what a mask is, and why `temps[temps > 30]` cannot keep the 2D shape.

In [52]:
mask = temps > 30
counts = mask.sum(axis=1)
print("B3a - readings above 30 per city: ", counts)

kathmandu_mask = mask[0]
print("B3b - Kathmandu above 30: ", days[kathmandu_mask])

# A mask is boolean masks which contins the boolean value of True where it satisfy the condition and False otherwise.

# temps[temps>30] - This returns the matching elements only in 1d array instead of 2d.

B3a - readings above 30 per city:  [1 2 1 2 6]
B3b - Kathmandu above 30:  ['D04']


### B4 — Views vs. copies (3 pts)
Take a slice of one city's first three days, set its first element to changed. Repeat with `999`, and print the original array to prove it.`copy()` and prove it did not. In a comment, explain in two sentences why NumPy defaults to a view, and what bug this causes if you forget.

In [59]:
city_slice = temps[0, 0:3]
print(city_slice)

city_slice[0] = 999
print("Original array after modification is: ",temps)

# reset to 29
temps[0,0] = 29

# using copy() method
city_copy = temps[0, 0:3].copy()
city_copy[0] = 999
print("Original array after modification is: ",temps)

# Numpy defaults to a view because it is faster and more memory efficient than creating a new copy of the data.

# If we forget that a slice is a view, modifying the slice can accidentally modify the original array and cause unexpected bugs.

[29. 18. 17.]
Original array after modification is:  [[999.  18.  17.  33.  21.  28.  22.  28.  24.  22.  21.  20.  18.  30.]
 [ 21.  26.  14.  25.  20.  33.  26.  19.  35.  30.  14.  16.  23.  28.]
 [ 20.  18.  28.  23.  17.  nan  22.  33.  30.  15.  14.  30.  26.  21.]
 [ 24.  23.  17.  14.  21.  14.  35.  18.  17.  15.  17.  15.  33.  18.]
 [ 33.  15.  19.  23.  31.  16.  33.  32.  32.  35.  17.  nan  29.  30.]]
Original array after modification is:  [[29. 18. 17. 33. 21. 28. 22. 28. 24. 22. 21. 20. 18. 30.]
 [21. 26. 14. 25. 20. 33. 26. 19. 35. 30. 14. 16. 23. 28.]
 [20. 18. 28. 23. 17. nan 22. 33. 30. 15. 14. 30. 26. 21.]
 [24. 23. 17. 14. 21. 14. 35. 18. 17. 15. 17. 15. 33. 18.]
 [33. 15. 19. 23. 31. 16. 33. 32. 32. 35. 17. nan 29. 30.]]


### B5 — Vectorization vs. a Python loop (4 pts)
Convert `temps` to Fahrenheit two ways: with an explicit loop (the only loop allowed in Part B) and with one vectorized expression. Confirm they agree with `np.allclose`. Then time both on an array of 1,000,000 values using `time.perf_counter()`, and print both timings plus the speedup as a multiple (`~Nx faster`). In a comment, explain where the loop's extra time actually goes.

In [70]:
fahrenheit_loop = []

for c in temps:
    fahrenheit_loop.append(c * 9/5 +32)

print("Using the loop: ",fahrenheit_loop)

# vectorized way
fahrenheit_vectorized = temps * 9/5 + 32
print("Using the vectorized: ",fahrenheit_vectorized)

print("B5 — Agree:",np.allclose(fahrenheit_loop, fahrenheit_vectorized)) # This produce false becasue of nan value in both array which are treated differently.

print("B5 — Agree:",np.allclose(fahrenheit_loop, fahrenheit_vectorized, equal_nan=True))


Using the loop:  [array([84.2, 64.4, 62.6, 91.4, 69.8, 82.4, 71.6, 82.4, 75.2, 71.6, 69.8,
       68. , 64.4, 86. ]), array([69.8, 78.8, 57.2, 77. , 68. , 91.4, 78.8, 66.2, 95. , 86. , 57.2,
       60.8, 73.4, 82.4]), array([68. , 64.4, 82.4, 73.4, 62.6,  nan, 71.6, 91.4, 86. , 59. , 57.2,
       86. , 78.8, 69.8]), array([75.2, 73.4, 62.6, 57.2, 69.8, 57.2, 95. , 64.4, 62.6, 59. , 62.6,
       59. , 91.4, 64.4]), array([91.4, 59. , 66.2, 73.4, 87.8, 60.8, 91.4, 89.6, 89.6, 95. , 62.6,
        nan, 84.2, 86. ])]
Using the vectorized:  [[84.2 64.4 62.6 91.4 69.8 82.4 71.6 82.4 75.2 71.6 69.8 68.  64.4 86. ]
 [69.8 78.8 57.2 77.  68.  91.4 78.8 66.2 95.  86.  57.2 60.8 73.4 82.4]
 [68.  64.4 82.4 73.4 62.6  nan 71.6 91.4 86.  59.  57.2 86.  78.8 69.8]
 [75.2 73.4 62.6 57.2 69.8 57.2 95.  64.4 62.6 59.  62.6 59.  91.4 64.4]
 [91.4 59.  66.2 73.4 87.8 60.8 91.4 89.6 89.6 95.  62.6  nan 84.2 86. ]]
B5 — Agree: False
B5 — Agree: True


In [ ]:
import time

array = np.random.randint(0, 100, size=1000000).astype(float)

start = time.perf_counter()
fahrenheit_loop = []
for c in array:
    fahrenheit_loop.append(c * 9/5 + 32)
end = time.perf_counter()
loop_time = end - start

start = time.perf_counter()
fahrenheit_vectorized = array * 9/5 + 32
end = time.perf_counter()
vectorized_time = end - start


speedup = loop_time / vectorized_time

print("B5 — Loop time:", loop_time)
print("B5 — Vectorized time:", vectorized_time)
print("B5 — Speedup:", speedup, "x")

# loop performs the python level operations repeatedly. Loop access each element. Loop takes time to append each result to python list.

B5 — Loop time: 0.21925610000107554
B5 — Vectorized time: 0.008114399999612942
B5 — Speedup: 27.02061766877823 x


### B6 — Broadcasting (4 pts)
(a) Compute each city's own fortnight average with a NaN-aware function and `keepdims=True`, then subtract it from `temps` to get an anomaly grid; print the result's shape and confirm it is still `(5, 14)`. 

(b) Apply a per-day sensor correction of shape `(14,)` to all five cities in one expression. 

(c) Attempt `temps + np.array([1, 2, 3, 4, 5])`, catch the `ValueError`, print its message, and explain in a comment why aligning shapes from the right makes this fail while (b) succeeds.

In [ ]:
temp_avg = temps.mean(axis = 1, keepdims = True)
temp_avg # This returns the nan as the average for the city which contains the  nan value so for NaN-aware function we will use np.nanmean()

array([[23.64285714],
       [23.57142857],
       [        nan],
       [20.07142857],
       [        nan]])

In [84]:
temp_avg = np.nanmean(temps, axis = 1, keepdims = True)
print("B6a - NaN-aware function: \n" ,temp_avg)

anomaly_grid = temps - temp_avg
print("\n B6a - anomaly grid: \n" ,anomaly_grid)
print("\n Shape of resulting grid: " ,anomaly_grid.shape)

B6a - NaN-aware function: 
 [[23.64285714]
 [23.57142857]
 [22.84615385]
 [20.07142857]
 [26.53846154]]

 B6a - anomaly grid: 
 [[  5.35714286  -5.64285714  -6.64285714   9.35714286  -2.64285714
    4.35714286  -1.64285714   4.35714286   0.35714286  -1.64285714
   -2.64285714  -3.64285714  -5.64285714   6.35714286]
 [ -2.57142857   2.42857143  -9.57142857   1.42857143  -3.57142857
    9.42857143   2.42857143  -4.57142857  11.42857143   6.42857143
   -9.57142857  -7.57142857  -0.57142857   4.42857143]
 [ -2.84615385  -4.84615385   5.15384615   0.15384615  -5.84615385
           nan  -0.84615385  10.15384615   7.15384615  -7.84615385
   -8.84615385   7.15384615   3.15384615  -1.84615385]
 [  3.92857143   2.92857143  -3.07142857  -6.07142857   0.92857143
   -6.07142857  14.92857143  -2.07142857  -3.07142857  -5.07142857
   -3.07142857  -5.07142857  12.92857143  -2.07142857]
 [  6.46153846 -11.53846154  -7.53846154  -3.53846154   4.46153846
  -10.53846154   6.46153846   5.46153846   5.4615

In [92]:
np.random.seed(42)
correction = np.random.randn(14)
corrected_temps = temps + correction
print(corrected_temps)

[[29.49671415 17.8617357  17.64768854 34.52302986 20.76584663 27.76586304
  23.57921282 28.76743473 23.53052561 22.54256004 20.53658231 19.53427025
  18.24196227 28.08671976]
 [21.49671415 25.8617357  14.64768854 26.52302986 19.76584663 32.76586304
  27.57921282 19.76743473 34.53052561 30.54256004 13.53658231 15.53427025
  23.24196227 26.08671976]
 [20.49671415 17.8617357  28.64768854 24.52302986 16.76584663         nan
  23.57921282 33.76743473 29.53052561 15.54256004 13.53658231 29.53427025
  26.24196227 19.08671976]
 [24.49671415 22.8617357  17.64768854 15.52302986 20.76584663 13.76586304
  36.57921282 18.76743473 16.53052561 15.54256004 16.53658231 14.53427025
  33.24196227 16.08671976]
 [33.49671415 14.8617357  19.64768854 24.52302986 30.76584663 15.76586304
  34.57921282 32.76743473 31.53052561 35.54256004 16.53658231         nan
  29.24196227 28.08671976]]


In [94]:
try:
    result = temps + np.array([1,2,3,4,5])
except ValueError as e:
    print("B6c - ValueError: ", e)

# Broadcasting aligns shapes from right and when it compare the shapes of temps which is (5,14) and (5,), numpy founds 14 != 5 
# so numpy cannot broadcast the results.

# But (b) succeeds because the shapes of temp and correction is (5,14) and (14,). When numpy compare the dimension from rights 
# it found both 14 so it broadcast it.

B6c - ValueError:  operands could not be broadcast together with shapes (5,14) (5,) 


### B7 — Matrix multiplication (4 pts)
(a) On the grocery-basket example (`quantities = [2, 3, 1]`, `prices = [120, 90, 250]`), print both `*` and `@`, and state in a comment what each returned and why they differ. 

(b) Build `features` of shape `(14,2)` whose columns are the across-city NaN-aware mean temperature and mean humidity per day, define `weights = np.array([0.6, -0.1])`, and compute a comfort score per day with `@`. Print the shapes of `features`, `weights`, and the result, and explain in a comment why the inner dimensions had to match.

In [ ]:
quantities = np.array([2, 3, 1])
prices = np.array([120, 90, 250])

print("B7a - *: ", quantities * prices)
print("B7a - @: ", quantities @ prices)

# * performs element-wise multiplication:
# [2*120, 3*90, 1*250] = [240, 270, 250]
#
# @ performs dot product and gives the total grocery cost:
# (2*120) + (3*90) + (1*250) = 760

B7a - *:  [240 270 250]
B7a - @:  760


In [107]:
mean_temperature = np.nanmean(temps, axis = 0)
mean_humidity = np.nanmean(humidity, axis = 0)
features = np.array([mean_temperature, mean_humidity]).T
print("B7b - Shape of features is: ",features.shape)

weights = np.array([0.6, -0.1])
print("B7b - Shape of weights is: ",weights.shape)

result = features @ weights
print("B7b - Comfort score per day with @: ", result)
print("B7b - Shape of result is: ",result.shape)

# Matrix Multiplication requires the inner dimensions to match. features has shape (14,2) and weights has shape (2,), 
# so the inner dimension 2 matches and the result has shape (14,).

B7b - Shape of features is:  (14, 2)
B7b - Shape of weights is:  (2,)
B7b - Comfort score per day with @:  [ 9.06  5.32  4.16  6.58  5.06  6.39  9.16  8.74 11.26  7.22  2.6   6.43
  8.66  8.16]
B7b - Shape of result is:  (14,)


### B8 — Aggregating along an axis (4 pts)
Using NaN-aware aggregations, print: mean, max, min and std per city; mean and max per day; and each city's hottest day as a day label (use `argmax`, then index `days`). State each result's shape. In a comment, state what `axis=0` and `axis=1` collapse here, in terms of this dataset.

In [128]:
mean_per_city = np.nanmean(temps, axis = 1)
print("B8 - NaN-aware aggregations - mean per city: " ,mean_per_city)
print("B8 - Shape of mean per city: " ,mean_per_city.shape)

max_per_city = np.nanmax(temps, axis = 1)
print("B8 - NaN-aware aggregations - max per city: " ,max_per_city)
print("B8 - Shape of max per city: " ,max_per_city.shape)

min_per_city = np.nanmin(temps, axis = 1)
print("B8 - NaN-aware aggregations - min per city: " ,min_per_city)
print("B8 - Shape of min per city: " ,min_per_city.shape)

std_per_city = np.nanstd(temps, axis = 1)
print("B8 - NaN-aware aggregations - std per city: " ,std_per_city)
print("B8 - Shape of std per city: " ,std_per_city.shape)


mean_per_day = np.nanmean(temps, axis = 0)
print("\nB8 - NaN-aware aggregations - mean per day: " ,mean_per_day)
print("B8 - Shape of mean per day: " ,mean_per_day.shape)

max_per_day = np.nanmax(temps, axis = 0)
print("\nB8 - NaN-aware aggregations - max per day: " ,max_per_day)
print("B8 - Shape of max per day: " ,max_per_day.shape)


hottest_day_index = np.nanargmax(temps, axis = 1)
hottest_day = days[hottest_day_index]

print("\nB8 - NaN-aware aggregations - Hottest day for each city: " ,hottest_day)
print("Shape of Hottest day: ", hottest_day.shape)


# axis=0 collapses the city dimension (rows),
# giving one result for each of the 14 days.
#
# axis=1 collapses the day dimension (columns),
# giving one result for each of the 5 cities.

B8 - NaN-aware aggregations - mean per city:  [23.64285714 23.57142857 22.84615385 20.07142857 26.53846154]
B8 - Shape of mean per city:  (5,)
B8 - NaN-aware aggregations - max per city:  [33. 35. 33. 35. 35.]
B8 - Shape of max per city:  (5,)
B8 - NaN-aware aggregations - min per city:  [17. 14. 14. 14. 15.]
B8 - Shape of min per city:  (5,)
B8 - NaN-aware aggregations - std per city:  [4.89324816 6.41108733 5.89453663 6.41943796 7.11028924]
B8 - Shape of std per city:  (5,)

B8 - NaN-aware aggregations - mean per day:  [25.4  20.   19.   23.6  22.   22.75 27.6  26.   27.6  23.4  16.6  20.25
 25.8  25.4 ]
B8 - Shape of mean per day:  (14,)

B8 - NaN-aware aggregations - max per day:  [33. 26. 28. 33. 31. 33. 35. 33. 35. 35. 21. 30. 33. 30.]
B8 - Shape of max per day:  (14,)

B8 - NaN-aware aggregations - Hottest day for each city:  ['D04' 'D09' 'D08' 'D07' 'D10']
Shape of Hottest day:  (5,)


### B9 — Reproducible randomness and a train/test split (3 pts)
Flatten `temps` to 70 samples. With `np.random.seed(42)`, shuffle an index array and split it 80/20 into train and test index sets; print both shapes, confirm they sum to 70, and confirm they share no index. Re-seed with 42, repeat, and assert the split is identical. In a comment, explain why you shuffle before splitting, and why the seed matters when you share results.

In [152]:
flattened = temps.flatten()
print(flattened)

index = np.arange(flattened.size)
np.random.seed(42)
np.random.shuffle(index)

# split
split_point = int(0.8 * len(index))

train_idx = index[:split_point]
test_idx = index[split_point:]

print("B9 - Train index shape: ",train_idx.shape)
print("B9 - Test index shape: ", test_idx.shape)

print("B9 - confirm shape sum to 70: ", len(train_idx) + len(test_idx))

# train and test has no common indices
print("B9 - Share no index: ",len(np.intersect1d(train_idx, test_idx)))


# Repeat the exact same process with the same seed
index2 = np.arange(flattened.size)

np.random.seed(42)  # for conforming simply comment and uncomment this line 

np.random.shuffle(index2)

# split
split_point2 = int(0.8 * len(index2))

train_idx2 = index2[:split_point2]
test_idx2 = index2[split_point2:]

print("\nB9 - Repeated Train index shape: ",train_idx2.shape)
print("B9 - Repeated Test index shape: ", test_idx2.shape)

assert np.array_equal(train_idx, train_idx2)
assert np.array_equal(test_idx, test_idx2)

print("Repeated split is identical: True")

# We shuffle before splitting so that the train and test sets are randomly selected rather than simply taking the first 80% and 
# last 20% of the data.
# 
# The seed matters because it makes the random shuffle reproducible. Anyone using the same data and seed can reproduce the same split.

[29. 18. 17. 33. 21. 28. 22. 28. 24. 22. 21. 20. 18. 30. 21. 26. 14. 25.
 20. 33. 26. 19. 35. 30. 14. 16. 23. 28. 20. 18. 28. 23. 17. nan 22. 33.
 30. 15. 14. 30. 26. 21. 24. 23. 17. 14. 21. 14. 35. 18. 17. 15. 17. 15.
 33. 18. 33. 15. 19. 23. 31. 16. 33. 32. 32. 35. 17. nan 29. 30.]
B9 - Train index shape:  (56,)
B9 - Test index shape:  (14,)
B9 - confirm shape sum to 70:  70
B9 - Share no index:  0

B9 - Repeated Train index shape:  (56,)
B9 - Repeated Test index shape:  (14,)
Repeated split is identical: True


### B10 — `np.where`, `argmax`, `argmin` (3 pts)
(a) Label every reading `"hot"` / `"mild"` / `"cold"` (above 30, 22–30, below 22) with nested `np.where`, print the label grid's shape. 

(b) Given `scores = np.array([0.08, 0.62, 0.21, 0.09])` and `labels = ["rain", "clear", "cloudy", "fog"]`, print the predicted label using `argmax`. In a comment, explain classifier needs `argmax` rather than `max`.

In [153]:
label_grid = np.where(temps > 30, "hot",
                      np.where(temps >= 22, "mild", "cold")
                    )
print("B10a - Label grid: ", label_grid)
print("B10a - Label grid shape: ", label_grid.shape)

B10a - Label grid:  [['mild' 'cold' 'cold' 'hot' 'cold' 'mild' 'mild' 'mild' 'mild' 'mild'
  'cold' 'cold' 'cold' 'mild']
 ['cold' 'mild' 'cold' 'mild' 'cold' 'hot' 'mild' 'cold' 'hot' 'mild'
  'cold' 'cold' 'mild' 'mild']
 ['cold' 'cold' 'mild' 'mild' 'cold' 'cold' 'mild' 'hot' 'mild' 'cold'
  'cold' 'mild' 'mild' 'cold']
 ['mild' 'mild' 'cold' 'cold' 'cold' 'cold' 'hot' 'cold' 'cold' 'cold'
  'cold' 'cold' 'hot' 'cold']
 ['hot' 'cold' 'cold' 'mild' 'hot' 'cold' 'hot' 'hot' 'hot' 'hot' 'cold'
  'cold' 'mild' 'mild']]
B10a - Label grid shape:  (5, 14)


In [156]:
scores = np.array([0.08, 0.62, 0.21, 0.09])
labels = ["rain", "clear", "cloudy", "fog"]

index = np.argmax(scores)
label = labels[index]

print("B10b - Predicted label: ", label)

# max() gives the largest score but a classifier needs to know which class has that score for that argmax() gives the index 
# of the largest score not the largest value.

B10b - Predicted label:  clear
